name: zam_rules
version: 0.3.0
description: A utility library that contains a set of most commonly used rules.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_rules
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  zam_block_architecture: ^0.3.0
  zam_core: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  zam_test: ^0.5.0
