name: zam_rules
version: 0.0.1
description: A utility library that contains a set of most commonly used rules.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_rules

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  zam_block_architecture: ^0.1.0
  zam_core: ^0.5.0

dev_dependencies:
  zam_test: ^0.3.0
