name: zam_rules
version: 0.2.0
description: A utility library that contains a set of most commonly used rules.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_rules

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  zam_block_architecture: ^0.2.0
  zam_core: ^0.6.0

dev_dependencies:
  lints: ^1.0.1
  zam_test: ^0.4.0
